### ISSUE TITLE
Run server while rendering

### ISSUE THREAD

**Issue by karellm** [ef4/prember#20]
I'm running a bunch of experimentations to build a static site with Ember. One of the requirements I'd like to meet is to have a flat file "database" without running an external API. To do that I tweaked `ember generate server`. You can see a code sample [here](https://github.com/karellm/montrealists.com/commit/830270ecd1a2c87779760c84136fcd9f923cd5ba#diff-0861d6d6b50d7d695344bf2d86d6e5e6) and an article about this [here](https://emberigniter.com/quickest-backend-api-for-ember/).  

It worked well prior installing Fastboot or prember. Though after installing them, I get `Error: Ember Data Request GET /posts returned a 404`. I guess you don't run the server when rendering. Would you mind adding an option to run the server, or do it automatically if present? Thanks!

**Comment by ef4** [comment]
I would suggest refactoring your build so that it writes out all the JSON files directly into the built app. That would make it work when rendered in prember, and it will _also_ make it work when it boots in the user's browser (a case that I think is broken in your example).

The simplest example of this is to just have a `public/posts.json` file in your app. That can be fetched both during prember prerendering and from a live app. Of course if you actually want separate files for the individual posts, you'd need to do a little more work during the build process to copy them all out of the posts.json file into `posts/1.json`, `posts/2.json`, etc.

**Comment by karellm** [comment]
Thanks for taking the time to answer. As a disclaimer, I'm not very familiar yet with ember build internals. And I'm aware that I'm trying to use Ember in a weird manner.

Do you mean that you would include the JSON files so that they can be fetched in production? They would live in the `/data` folder to be fetched/edited in development, then included for the production build and every page would fetch the data it needs to render. Do I understand your suggestion correctly?

I guess my initial goal was to use Ember as some sort of a CMS to generate a purely static website. In production, it would render the HTML making it pointless to grab the JSON data. I might have been wrong assuming that `prember` would generate pages and skip the route `model()` call. The error I'm getting clearly comes from the route trying to fetch the JSON. Maybe I could write conditional code based on the environment to only fetch the JSON in development.

**Comment by ef4** [comment]
> Do I understand your suggestion correctly?

Yes.

> I guess my initial goal was to use Ember as some sort of a CMS to generate a purely static website. In production, it would render the HTML making it pointless to grab the JSON data. I might have been wrong assuming that prember would generate pages and skip the route model() call.

That sounds possible but it's not what prember does normally. Prember doesn't interfere with the normal Ember app booting, so your model hooks would still all be running in production unless you do something custom to prevent that.

If you really want a totally static site, you should probably find a way to strip the `<script>` tags out of the final HTML so the app never loads or boots at all.

> The error I'm getting clearly comes from the route trying to fetch the JSON. Maybe I could write conditional code based on the environment to only fetch the JSON in development.

You definitely need to fetch the JSON when prember is rendering, so if that depends on having a server running you may just need to start the server first yourself before running the build.

**Comment by sandstrom** [comment]
@karellm I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by karellm** [comment]
I've dropped this exploration a long time ago so let's close it and it can always be reopened if need be. Happy gardening 😄
