### ISSUE TITLE
Cannot read property 'lookup' of undefined

### ISSUE THREAD

**Issue by lougreenwood** [ef4/prember#22]
Hi, I'm getting this error - it started some time in the past couple of weeks, but I didn't take much notice of the error for various reasons.

I've tried rolling back all of the add-ons I've added since I know Prember was working, but that hasn't helped.

Is there any way to get a more verbose error, so I can understand where this lookup call is happening?

```
index failed with exception: TypeError: Cannot read property 'lookup' of undefined
pre-render privacy failed with exception: TypeError: Cannot read property 'lookup' of undefined
pre-render security failed with exception: TypeError: Cannot read property 'lookup' of undefined
pre-render terms failed with exception: TypeError: Cannot read property 'lookup' of undefined
pre-render contact-us failed with exception: TypeError: Cannot read property 'lookup' of undefined
pre-render blog failed with exception: TypeError: Cannot read property 'lookup' of undefined
pre-render pricing failed with exception: TypeError: Cannot read property 'lookup' of undefined
pre-render about-us failed with exception: TypeError: Cannot read property 'lookup' of undefined
pre-render press failed with exception: TypeError: Cannot read property 'lookup' of undefined
pre-render testimonials failed with exception: TypeError: Cannot read property 'lookup' of undefined
```

**Comment by ef4** [comment]
You should see the same error when running in development with `ember s` (assuming you don't disable fastboot). It should give a more complete stack trace then.

Or you can do 
  1. `node --inspect-brk ./node_modules/.bin/ember s` 
  2. Go to `chrome://inspect` in Chrome
  3. Click "open dedicated DevTools for node"
  4. Use the debugger to examine what is happening around the exception.
