### ISSUE TITLE
Prember shows errors when building for a non-production environment

### ISSUE THREAD

**Issue by ctataryn** [ef4/prember#27]
When I build my project using `ember build --environment=production` everything works exactly as it should.  However when I build using: `ember build --environment=beta` I get a whole slew of errors:

```
$ ember build --environment=beta
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
⠋ Building
Prember enabled: true

bootstrap-sassy config: all JS enabled, glyphicons enabled

/home/craiger/src/grind/crowdscriber-site/app/controllers/application.js
  56:25  error  'error' is defined but never used  no-unused-vars
  65:9   error  Do not use global `$` or `jQuery`  ember/no-global-jquery
  65:9   error  '$' is not defined                 no-undef

✖ 3 problems (3 errors, 0 warnings)


/home/craiger/src/grind/crowdscriber-site/app/controllers/how-it-works.js
  13:9   error  '$' is not defined                 no-undef
  13:9   error  Do not use global `$` or `jQuery`  ember/no-global-jquery
  13:45  error  '$' is not defined                 no-undef
  13:45  error  Do not use global `$` or `jQuery`  ember/no-global-jquery
  19:9   error  '$' is not defined                 no-undef
  19:9   error  Do not use global `$` or `jQuery`  ember/no-global-jquery
  19:45  error  '$' is not defined                 no-undef
  19:45  error  Do not use global `$` or `jQuery`  ember/no-global-jquery
  25:9   error  '$' is not defined                 no-undef
  25:9   error  Do not use global `$` or `jQuery`  ember/no-global-jquery
  25:45  error  '$' is not defined                 no-undef
  25:45  error  Do not use global `$` or `jQuery`  ember/no-global-jquery
  31:9   error  '$' is not defined                 no-undef
  31:9   error  Do not use global `$` or `jQuery`  ember/no-global-jquery
  31:45  error  Do not use global `$` or `jQuery`  ember/no-global-jquery
  31:45  error  '$' is not defined                 no-undef
...
```
My `ember-cli-build.js` file looks like this:

```
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  let enablePrember = process.env.EMBER_ENV === 'production' || process.env.EMBER_ENV === 'beta';
  console.log(`\nPrember enabled: ${enablePrember}\n`);
  let app = new EmberApp(defaults, {
    // Add options here
    prember: {
      enabled: enablePrember,
      urls: [
        '/',
        '/about',
        '/pricing',
        '/how-it-works',
        '/screen-reader',
        '/contact'
      ]
    }
  });
  return app.toTree();
};
```
This being said, what Prember produces seems to work just fine.  I notice however that the `beta` build is much faster (even though it spits out all the errors) than the `production` build. I imagine that might have something to do with minifying that takes place when ember builds for production.

Here's a few examples, I sped up the production version as it was over a minute long:

Building for `production`
![prember-production](https://user-images.githubusercontent.com/435719/46781464-66435300-cce7-11e8-9c0c-9bedd7c06b08.gif)

Building for `beta`
![prember-beta](https://user-images.githubusercontent.com/435719/46781480-73f8d880-cce7-11e8-8795-3a6da5a1bb67.gif)

Does anyone know why building for the `beta` environment might display so many errors while building for `production` doesn't?

**Comment by ef4** [comment]
In general, ember-cli doesn't support adding arbitrary environments. Just three: development, test, and production. A lot of things will potentially break if you try to add more.

If you're trying to develop a `beta` version of your app, it's still a "development" environment. If you're trying to deploy it to a server, it's still a "production" environment.

You can always add your own environment variables to customize the app for different situations. And for deployment, ember-cli-deploy supports multiple targets, which may do what you want.

**Comment by ctataryn** [comment]
@ef4 Interesting.  I know this has nothing to do with prember, but I think it's a valid point for Ember to support extra environments.  For our project, we have 3: `development`, `beta`, `production`. Each has its own set of config files that contain environment-specific settings.

I've been happily building my Ember app using `--environment beta` for years now without a problem. It wasn't until I tried it with prember that I had issues.

**Comment by ctataryn** [comment]
@ef4 Thanks for the info. Based on your warnings, I did some research and I retro-fitted my app to use `ember-cli-dotenv`. Now I can create my `beta` builds via:

```
export BUILD_ENV=beta
ember build --environment production
```

I have some initialization in my `config/dotenv.js` file that picks the right `.env` file based on the `process.env.BUILD_ENV` var 👍
