### ISSUE TITLE
protocol missing in header

### ISSUE THREAD

**Issue by xg-wang** [ef4/prember#30]
https://github.com/ef4/prember/blob/v1.0.0/lib/prerender.js#L111
The protocol "http:" is missing here, is it intentional? This is causing some extra check for protocol `undefined:` like https://github.com/ember-cli/ember-fetch/pull/143/files#diff-2992dd665823759d28df78b0c59aff62

**Comment by ef4** [comment]
It's not intentional, happy to accept a PR.

This whole response object is unfortunately leaked from fastboot-express-middleware and wasn't ever carefully designed, which makes it hard to maintain compatibility when you run fastboot inside other contexts.
