### ISSUE TITLE
Prember don't works with Ember Engines

### ISSUE THREAD

**Issue by villander** [ef4/prember#37]
after run: PREMBER=true ember serve

I have this error 

```
Build Error (prember)

ENOENT: no such file or directory, open '/Users/villander/Projects/ember-engines.com/tmp/prember-input_base_path-Es7cJVr1.tmp/assets/node-asset-manifest.js'


Stack Trace and Error Report: /var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/error.dump.1935969b0430e3f7fb8908773f574f38.log
```

repo with reproduction - https://github.com/villander/ember-engines.com/tree/prember

cc: @ef4

**Comment by ef4** [comment]
Hi @villander thanks for sharing a reproduction.

I think this may be fixed by adding `ember-engines` to the `ember-addon.after` array in prember's `package.json`. Please give that a try.

**Comment by villander** [comment]
this worked @ef4 I opened a PR here https://github.com/ef4/prember/pull/39
