### ISSUE TITLE
Direct links redirect in Netlify deployment

### ISSUE THREAD

**Issue by allthesignals** [ef4/prember#41]
Hi there — I'm seeing seeing deep links to nested routes redirect to the index:

https://deploy-preview-935--labs-zola.netlify.com/l/lot/1/760/32 will redirect to https://deploy-preview-935--labs-zola.netlify.com/about

(the / index route does redirect to /about as intended).

Any ideas? Do I need to update my server configuration?

**Comment by allthesignals** [comment]
Here's my configuration:

```
    prember: {
      urls: [
        '/',
        '/about',
      ],
    },
```

Seems like when I remove `/`, I can get deep-linking of dynamic routes (with no pre-rendered content), but lose the pre-rendering altogether (unless it's linked directly to /about).

When I keep `/`, I lose deep-linking but keep pre-rendering. Pre-rendering _all_ the routers isn't feasible because it would be over 1 million pages.

**Comment by allthesignals** [comment]
Here's how I configured my Netlify server's redirects:

```
/    /index.html    200
/about    /about/index.html    200
/*    /_empty.html    200
```

The first two lines are the prember routes, the last line forces everything else to the regular index.html. This seems to work fine for me, but is this the "right" way (as in am I doing more work than is necessary because I'm missing something about how I've configured prember)? Also, if this is the right approach, how can we get this to work in [prember-middleware](https://github.com/ef4/prember-middleware)? I'm able to reproduce this issue locally using that.

Lemme know if I can help!

**Comment by ef4** [comment]
Yes, that is the right way. It's what's described in step 2 [here](https://github.com/ef4/prember#configuring-your-webserver).

prember-middleware is only needed if you want to locally test prember when using `ember s`. It shouldn't be related to deploying to netlify.

**Comment by allthesignals** [comment]
@ef4 thanks! Right, what I'm saying is I can't seem to test prember correctly without the ability to configure these redirects in the middleware.

**Comment by ef4** [comment]
I'm not sure I understand the problem you're hitting. 

Which redirect doesn't happen when using prember-middleware?

**Comment by allthesignals** [comment]
@ef4 Sure, sorry I'm not explaining very well: the problem I'm hitting locally in development is that when I go to a subroute that isn't pre-rendered (http://localhost:4200/l/lot/1/1445/31), it redirects to my route that _is_ pre-rendered (http://localhost:4200/about). I do have the prember middleware installed.

I think this is because I need to configure the local webserver to point non-pre-rendered routes to `_empty.html`, but I'm not sure there's a way to do that just yet. Or I'm doing something wrong, which is the likelier explanation.

This isn't a huge problem but I'm curious why. It would just help to be able to confirm correct behavior in the development environment.

Thanks!

**Comment by ef4** [comment]
Ah, so in development ember-cli always serves the normal (empty) `index.html` by default, for any URL that isn't otherwise handled. There's no need to set anything up to use `_empty.html` because that's what ember-cli always does.

What is causing the redirect from `/l/lot/1/1445/31` to `/about`? That is not something prember would do.

Maybe things are getting confused because ember-cli-fastboot is running in development. *All* your routes are going to get rendered by fastboot, whether you told prember to pre-build them or not. Maybe try setting `FASTBOOT_DISABLED=true` environment variable to rule that out.
