### ISSUE TITLE
Use with ember-cli-deploy-s3-index

### ISSUE THREAD

**Issue by adambedford** [ef4/prember#55]
I'm trying to get this wired up to our deploy pipeline that uses `ember-cli-deploy-s3-index` for `index.html` (and soon hopefully `_error.html`, `about.html` etc...).

I skipped adding the suggested `filePattern` to the `ember-cli-deploy-s3` config, and instead added:

```
filePattern: '**/*.{html}'
```

to the `ember-cli-deploy-s3-index` config. 

Unfortunately, that's throwing the following error during deployment:

```
Error: ENOENT: no such file or directory, open 'tmp/deploy-dist/**/*.{html}'
Error: ENOENT: no such file or directory, open 'tmp/deploy-dist/**/*.{html}'
Pipeline aborted
```

Now I'm not sure what the source of the error is -- I wonder whether `-s3-index` requires a different `filePattern`, or perhaps we need to change the base `distDir`. Is there anything particular about Prember that would prevent this approach?

**Comment by LevelbossMike** [comment]
Answered here: https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index/issues/82
