### ISSUE TITLE
Usage with Fastboot in production

### ISSUE THREAD

**Issue by adambedford** [ef4/prember#58]
I'll preface this by saying I'm not entirely sure this makes sense and am still figuring out the best approach, but...

Does it make sense to use Prember with Fastboot in production? i.e. We're currently using Fastboot but I'd like to speed up some of the marketing pages (the app and website are all a single Ember app). Would installing Prember give us any value? Probably not, right, since traffic is still being directed to the Node server.

A more complicated solution would be to use a reverse proxy to forward the marketing routes to Prember-built static files on Cloudfront/S3 and leave everything else going to the Fastboot app.

Has anyone done anything like this? I have a slight suspicion I'm overcomplicating things.

**Comment by ef4** [comment]
If you're already hosting a fastboot server in production, I don't think you gain much by adding prember. You can get the same effect by putting a caching CDN in front of your fastboot server and configuring it to cache the routes that you would have pre-rendered in prember.
