### ISSUE TITLE
Small error in Prember 2.0.0 release notes

### ISSUE THREAD

**Issue by IgnaceMaes** [ef4/prember#80]
The release notes mention the following:

> breaking: Drop support for Node 16 and Fix CI by @mansona in https://github.com/ef4/prember/pull/79

But according to the change Node 16 is still supported and now the minimum version. Should this be `< Node 16`?

https://github.com/ef4/prember/releases/tag/v2.0.0

**Comment by mansona** [comment]
Yes that's totally right 🙈

**Comment by mansona** [comment]
I've updated it there now 👍
